version: 2

project_name: pocketbase

dist: .builds

before:
  hooks:
    - go mod tidy

builds:
  - id: build_noncgo
    main: ./examples/base
    binary: pocketbase
    ldflags:
      - -s -w -X github.com/pocketbase/pocketbase.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - s390x
      - ppc64le
    goarm:
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: s390x
      - goos: windows
        goarch: ppc64le
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: s390x
      - goos: darwin
        goarch: ppc64le

release:
  draft: true

archives:
  - id: archive_noncgo
    builds: [build_noncgo]
    format: zip
    files:
      - LICENSE.md
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: '{{ incpatch .Version }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^examples:'
      - '^ui:'
