site_name: Vaccine Cold Chain Monitoring
repo_url: https://github.com/ibm-cloud-architecture/vaccine-cold-chain.git
nav:
  - Introduction: 
    - What you will learn: index.md
  - Environments:
    - Event Streams environment: environments/event-streams.md
    - MongoDB on IBM Cloud: environments/mongo.md
    - Postgresql on IBM Cloud: environments/postgresql.md
    - Cloud Pak for Data: environments/cp4d.md
  - AI Ladder:
    - Collect:
      - Preparing data for demonstration:
        - Generate telemetry data: collect/generate-telemetry.md
      - Data ingestion and in motion with Cloud Pak for Integration: collect/cp4i-es.md
      - Collect data with Cloud Pak for Data: collect/cp4d-collect-data.md
    - Analyze: 
      - Define the anomaly detection scoring model with Watson Studio: analyze/ws-ml-dev.md
    - Infuse:
      - Develop the simulation app: infuse/simul-app.md
      - Develop scoring app with cloud pak for application: infuse/dev-scoring.md
      - Build and run the solution on Openshift: infuse/build-run.md
      - Run integration tests: infuse/integration-tests.md
      - Engineer dispatching with Business process with Cloud Pak for Automation: bpm/readme.md
  - Devops: 
    - Develop the simulation app: infuse/simul-app.md
    - Develop the scoring app with event messaging and microprofile: infuse/dev-scoring.md
    - Continuous Integration: devops/ci.md
    - Continuous Deployment: devops/cd.md
  - Engineer dispatching with Business process with Cloud Pak for Automation: bpm/readme.md
  - Compendium: compendium.md

theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences