name: Build and Push API Gateway Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "src/api-gateway/**"
      - ".github/workflows/api-gateway.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/api-gateway
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: src/api-gateway/
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=ghcr.io/jadonharsh109/istio-microservice-deployment-api:cache
          push: true
          tags: ghcr.io/jadonharsh109/istio-microservice-deployment-api:latest
